version: "3.9"
services:
    mysqldb:
        image: mysql:latest
        restart: always
        ports:
            - 3360:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "true"
            MYSQL_DATABASE: "AssociationCoranique"
        volumes:
            - db:/var/lib/mysql
    express:
        depends_on:
            - mysqldb
        build: .
        restart: unless-stopped
        ports:
            - 4000:5000
        stdin_open: true
        tty: true
        volumes:
            - ./src:/app/src/

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8099:80
        environment:
            - PMA_ARBITRARY=1

volumes:
    db:
