version: "3.9"
services:
    mysqldb:
        image: mysql:5.7
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - db:/var/lib/mysql

    express:
        depends_on:
            - mysqldb
        build: .
        restart: unless-stopped
        ports:
            - 5000:5000
        stdin_open: true
        tty: true
        volumes:
            - ./src:/app/src/

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1

volumes:
    db:
